version: '3.3'
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=mysecretpassword
      - PGDATA=/var/lib/postgresql/data/pgdata
    container_name: db
    networks: 
      - app

  flask:
    build: .
    command: gunicorn -w 3 run:app --preload -b 0.0.0.0:5000
    ports:
      - "5000:5000"
    depends_on:
      - db
    container_name: flask
    networks:
      app:
        aliases:
          - flask-app

  nginx:
    image: nginx
    depends_on:
      - flask
    container_name: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - app

networks:
  app:
